# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: gartico_db
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      
    ports:
      - ${DATABASE_PORT}:3306